### PR TITLE
Set status of AEP 002 to implemented.

### PR DESCRIPTION
**Pull request by csadorf**
AEP 002 has been implemented, because the community has appointed a dependency manager and the recommendations outlined in the AEP are implemented as part of the aiida-core dependency specification and CI workflow.

### CODE REVIEW

**Comment by sphuber** [comment]
Is there a place where it is documented what the available values are for the status attribute?

**Comment by csadorf** [comment]
> @csadorf Is there a place where it is documented what the available values are for the status attribute?

The possible values for _status_ are discussed here: https://github.com/aiidateam/AEP/tree/master/000_aep_guidelines#detailed-explanation

**Comment by sphuber** [comment]
Is AEP 000 a special case or should that also be changed to "implemented"?

**Comment by csadorf** [comment]
> Is AEP 000 a special case or should that also be changed to "implemented"?

No idea.

**Comment by kjappelbaum** [comment]
I would set it to "implemented" following a bit how meta-PEPs are treated (https://www.python.org/dev/peps/pep-0001/).
"Some Informational and Process PEPs may also have a status of "Active" if they are never meant to be completed. E.g. PEP 1 (this PEP)." PEP1 is also "active"

**Comment by csadorf** [comment]
It seems to me like we will need to have a meta discussion about this. Honestly, for the process AEPs, _active_ appears a bit more natural to me than _implemented_.

**Pull request merged**
